import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
const inter = Inter({ subsets: ["latin"] });
import Modal from "react-modal"

export default function Home() {
  return (
    <>
      <Head>
        <title>Tutorial Template Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <div className={styles["video-block"]} >
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles["video-block"]} >
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles["video-block"]}>
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles["video-block"]} >
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles["video-block"]} >
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles["video-block"]} >
              <video>
                <source src="/video.mp4" type="video/mp4"></source>
              </video>
            </div>
            <div
              className={styles['video-content-block']}
            >
              <div className= {styles['video-title-name']}>
                <h3>Video Title - Lorem Ipsum</h3>
              </div>
              <div className="video-description">
                <p>
                  Introduction to Deceptive Sexuality and Trauma (DST).
                  Sexuality and Trauma (DST).Sexuality and Trauma (DST).
                </p>
              </div>
              <div className={styles["video-play-btn"]}>
                <Button type="button" className={styles["play-btn"]} variant="outlined">
                  Watch Now
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
